export {
  SDK_VERSION,
} from "./version.ts";
export {
  themeTokens,
  themeVar,
} from "./theme-tokens.ts";

export {
  defineShellComponent,
  defineShellConfig,
  diffShellLayouts,
  shellComponent,
  shellSurface,
} from "../shell/index.ts";
export {
  applyWindowManagerEvent,
  closeWindow,
  collectWindowManagerIntents,
  computeWindowManagerIntents,
  createWindowModel,
  focusNextWindow,
  focusPrevWindow,
  focusPreviousWindow,
  focusWindow,
  focusedWindowId,
  layout,
  maximizeWindow,
  minimizeWindow,
  moveResizeWindow,
  moveWindow,
  moveWindowToWorkspace,
  openWindow,
  reduceWindowManagerEvent,
  reduceWindowModel,
  requestMoveResize,
  resizeWindow,
  setWorkspaceLayout,
  stackWorkspace,
  switchWorkspace,
  tileWorkspace,
} from "../wm/policy.ts";
export {
  CompositorDriver,
  compositorWindowPlacement,
} from "../compositor-bridge/index.ts";
export {
  appSurfaceId,
  appWindowId,
} from "../appshell/index.ts";
export {
  NotificationCenter,
  TrayModel,
  createStaticShellCapabilityPort,
} from "../shell/notifications/index.ts";
export {
  createChromeNotificationState,
  createLaunchAppIntent,
  createPanelFocusIntent,
  filterLauncherApps,
  reduceChromeNotifications,
  reduceNotificationCenter,
} from "../shell/chrome/index.ts";
export {
  createFileManagerState,
  createSettingsAppState,
  emitSettingsControlPlaneIntent,
  fileManagerAppProps,
  fileManagerAppWindowRequest,
  firstPartyAppWindowRequests,
  joinCapabilityPath,
  loadFileManagerDirectory,
  navigateFileManager,
  parentCapabilityPath,
  readFileManagerFile,
  renderFileManagerAppSurface,
  renderSettingsAppSurface,
  requestSettingsApply,
  requestSettingsPreview,
  settingsAppProps,
  settingsAppWindowRequest,
  settleSettingsControlPlaneResult,
} from "../apps/index.ts";
export {
  DesktopUiPackageLoader,
  KNOWN_GOOD_DESKTOP_UI_PACKAGE_ID,
  createDesktopHostForPackage,
  hasDesktopCapabilityGrant,
  isSdkVersionCompatible,
  knownGoodDesktopUiPackage,
  loadUiPackage,
  validateDesktopUiPackageManifest,
} from "./loader.ts";

export type {
  EvaluatedShellConfig,
  RegisteredShellComponent,
  ShellApplyResult,
  ShellComponentDefinition,
  ShellComponentRender,
  ShellComponentRenderContext,
  ShellComponentRenderResult,
  ShellConfigDefinition,
  ShellConfigRender,
  ShellConfigRenderApi,
  ShellCssDefinition,
  ShellCssRule,
  ShellElement,
  ShellElementOptions,
  ShellError,
  ShellLayoutDiff,
  ShellManagedSnapshot,
  ShellPlacement,
  ShellPlacementInput,
  ShellPreviewResult,
  ShellRect,
  ShellResolvedSurface,
  ShellResult,
  ShellRollbackResult,
  ShellStyleSheet,
  ShellWindowManagerPlacementRequest,
  ShellWindowManagerPolicy,
} from "../shell/index.ts";
export type {
  CreateWindowModelOptions,
  LayoutConstraints,
  Rect,
  TextureId,
  WindowId,
  WindowManagerEvent,
  WindowManagerIntent,
  WindowMode,
  WindowModel,
  WindowOpenRequest,
  WindowPlacement,
  WindowState,
  WorkspaceId,
  WorkspaceLayoutMode,
  WorkspaceState,
} from "../wm/policy.ts";
export type {
  CompositorCommand,
  CompositorDriverError,
  CompositorPort,
  CompositorRect,
  CompositorReconcileInput,
  CompositorReconcileResult,
  CompositorSurfaceKind,
  CompositorSurfaceSize,
  CompositorSurfaceSnapshot,
  CompositorWindowPlacement,
} from "../compositor-bridge/index.ts";
export type {
  AppWindowHints,
  TsxAppDescriptor,
  TsxComponentRef,
  WebAppDescriptor,
  WebviewRuntimeRef,
} from "../appshell/index.ts";
export type {
  FilesEntry,
  FilesEntryKind,
  FilesErrorResponse,
  FilesFlatGrant,
  FilesGrant,
  FilesGrantAccess,
  FilesGrantRoles,
  FilesOperation,
  FilesRequest,
  FilesResponse,
  FilesRole,
  FilesRoleAccess,
  FilesSharedGrant,
  Role,
} from "../files-grant.ts";
export type {
  NotificationAction,
  NotificationActionInput,
  NotificationActionStyle,
  NotificationCenterOptions,
  NotificationCenterSnapshot,
  NotificationClock,
  NotificationGroup,
  NotificationIntent,
  NotificationPostInput,
  NotificationPriority,
  ShellCapabilityGrant,
  ShellCapabilityPort,
  ShellCapabilityRequest,
  ShellGrantCapability,
  ShellNotification,
  TrayIntent,
  TrayItem,
  TrayItemInput,
  TrayMenuItem,
  TrayMenuItemInput,
  TrayModelOptions,
  TraySnapshot,
  TrayStatus,
} from "../shell/notifications/index.ts";
export type {
  ChromeFocusedWindow,
  ChromeFocusWindowIntent,
  ChromeLaunchAppIntent,
  ChromeLauncherApp,
  ChromeLauncherState,
  ChromeNotification,
  ChromeNotificationClock,
  ChromeNotificationEvent,
  ChromeNotificationInput,
  ChromeNotificationSeverity,
  ChromeNotificationState,
  ChromePanelEdge,
  ChromePanelState,
  ChromeShellIntent,
  ChromeShellIntentPort,
  ChromeTrayStatus,
} from "../shell/chrome/index.ts";
export type {
  AppError,
  AppResult,
  FileManagerSelectedFile,
  FileManagerState,
  FileManagerStateInput,
  FileManagerStatus,
  FileManagerTransition,
  FilesCapabilityPort,
  SettingsAppState,
  SettingsApplyIntent,
  SettingsCategory,
  SettingsControlPlaneAccepted,
  SettingsControlPlaneIntent,
  SettingsControlPlanePort,
  SettingsControlPlaneResult,
  SettingsEdit,
  SettingsIntentTransition,
  SettingsManagedConfig,
  SettingsPendingEdit,
  SettingsPreviewIntent,
  SettingsValue,
  SettingsWidget,
  SettingsWidgetKind,
} from "../apps/index.ts";
export type {
  DesktopAppLaunch,
  DesktopAppStop,
  DesktopCapability,
  DesktopCapabilityGrant,
  DesktopHost,
  DesktopHostError,
  DesktopHostResult,
  DesktopLaunchableApp,
  DesktopLauncherIntent,
  DesktopMaybePromise,
  DesktopSdkCompatibility,
  DesktopSettingsApply,
  DesktopSettingsPreview,
  DesktopSettingsReadRequest,
  DesktopSettingsWriteRequest,
  DesktopTheme,
  DesktopThemeTokens,
  DesktopUiInstance,
  DesktopUiPackage,
  DesktopUiPackageManifest,
} from "./ui-package.ts";
export type {
  DesktopUiLoadedPackage,
  DesktopUiLoaderOptions,
  DesktopUiLoadResult,
  DesktopUiValidationError,
  DesktopUiValidationResult,
} from "./loader.ts";
export type {
  VitaThemeCssVariableName,
  VitaThemeTokenGroup,
  VitaThemeTokenGroups,
  VitaThemeTokenMap,
  VitaThemeTokenName,
  VitaThemeTokens,
  VitaThemeVarReference,
  VitaThemeVariant,
} from "./theme-tokens.ts";
